### ISSUE TITLE
[DLCV] 2018-02-10 질문사항

### ISSUE THREAD

**Issue by angrypark** [YBIGTA/data-science-2018#12]
U-net에 대한 이론적인 내용은 내일 더 준비해서 같이 설명하도록 하겠습니다. Image 쪽 kaggle 제출에 대해서 잘 몰랐던 분들에게 많은 도움이 될 것 같습니다!

**Comment by godongyoung** [comment]
사진이 몇개 보이지않는것같습니다ㅠ
글구 early stop에 대해 설명해주실수잇나요?

**Comment by hyejukim-ybigta** [comment]
Prediction rate이 얼마나 나오셨나요? 안 적혀있길래 궁금해서 여쭤봅니다

**Comment by ybigtaJH** [comment]
training sample 과 validation sample에서의 sanity는 얼마나 나왔나요??

**Comment by DabinJeong** [comment]
여기에 있는 네트워크 구조에 따르면 처음에는 이미지의 일부분을 보고, 그 부분 안에서 또 일부를 보고..이런식으로 계속 돋보기로 확대해가면서 보는 것처럼 되는 건가요? 잘 이해가 가지 않습니다...ㅠ

**Comment by SongChiYoung** [comment]
U Net의 컨셉이 기존 설명해주셨던 다른 net들과 차이가 무엇인지 잘 모르겠습니다
