### ISSUE TITLE
[ISL] 2018-02-10 질문사항

### ISSUE THREAD

**Issue by jungsooyun** [YBIGTA/data-science-2018#13]
https://jungsooyun.github.io/isl%20study/2018/02/07/Ch_6_Lasso_with_python.html

https://github.com/YBIGTA/data-science-2018/blob/master/ISL/18-02-09-Lasso_sklearn.ipynb

**Comment by SongChiYoung** [comment]
lasso regression?  Classification? 이 무엇인지 간략한 설명 부탁드립니다.

**Comment by KangBK0120** [comment]
http://3months.tistory.com/12

nbviewer를 쓰면 jupyter notebook 파일 자체를 업로드할 필요 없이 링크만으로 공유가 가능합니다!
jupyter notebook 파일은 로드하는데 시간이 좀 오래걸리니 이걸 사용하는 것도 괜찮을 것 같아요!

**Comment by godongyoung** [comment]
warm start의 의미에 대해 조금더설명해주실수잇나요?
글구 alpha가 유일한파라미터라하였는데, 파리미터와 하이퍼파라미터의 차이가뭔가요?

**Comment by Jooong** [comment]
하이퍼파라미터 tol에서 dual gap이라는게 (이전 iteration의 MSE - 새로운 iteration의 MSE) 를 의미하는걸까요?
