### ISSUE TITLE
[ISL] 2018-02-14 릴레이 질문(스터디 내부) 

### ISSUE THREAD

**Issue by hyejukim-ybigta** [YBIGTA/data-science-2018#15]
설을 맞아 즐거운(...) 릴레이-질문

**Comment by hyejukim-ybigta** [comment]
![image](https://user-images.githubusercontent.com/32008883/36202931-0acfaef8-11c9-11e8-86eb-02b63bef505b.png)
다음은 smoothing spline 과 관련된 함수로 minimize 시켜야 한다.  
(1)수식의 두 부분에 대해 간략히 설명하고 왜 minimize 시켜야하는지 설명하라(*g''(x)의 의미 포함) 
(2)또한 tuning parameter lambda의 변화에 따라 어떻게 의미가 달라지는 서술하여라

**Comment by ybigtaJH** [comment]
@hyejukim-ybigta 
(1)수식에서 왼쪽에 있는 것은 loss function으로 함수 g가 데이터에 잘 적합되도록 한다. 오른쪽에 있는 것은 penalty term으로 함수 g의 변동성을 제한한다. 이때, 2차 도함수는 함수 g의 roughness를 나타내는데, 이는 기울기의 변동성이라고 이해할 수 있다. 따라서 smooth하게 하기 위해서는 기울기의 변동성이 작아야하고 왼쪽에 있는 loss function이 RSS값인데, 이 값도 작게해야하므로 주어진 수식을 최소화해야한다.

(2)lambda 값이 0이라면 penalty term 이 효과가 없어지고 g의 변동성이 매우 커질 수 있다. 반대로 람다값이 양의 무한대로 발산하면 g는 거의 완전히 smooth해질 것이다.

질문: piecewise cubic 그래프(교재 272쪽 참고)에서 knot 부분에서 불연속적인 부분이 있을때, 이 그래프의 유연성이 크다고 하는데, 이를 자유도의 개념과 연관해서 설명하고, 이러한 방법을 해결하기 위해서는 어떠한 constraints를 추가하는지에 대해서 서술하여라

**Comment by statkim7578** [comment]
@ybigtaJH 

Answer)
piecewise cubic 그래프에서 knot가 증가하면 모형의 유연성이 증가하는데, 그 이유로는
knot가 증가할 수록 그에 비례해서 원래 추정해야할 parameter의 갯수가 증가하기 때문입니다.
'추정해야할 모수가 많아진다' -> '모형이 복잡해진다' -> '모형이 더 유연해진다' -> 'Variance는 증가하고, Bias는 감소한다'  ㅇㅈ? ㅇㅇㅈ

Question)
GAMs의 장점과 단점에 대해서 간단하게 설명해주세요.

**Comment by godongyoung** [comment]
답: 기존의 선형적합에서는 할 수 없던 비선형적합을 자동적으로 할 수 있게 한다. 고로 각 변수를 일일이 변형해줄 필요 없다. 

비선형적합인 만큼 예측력이 높다.

가법적인 모델이므로 다른 변수들이 고정되어 있을때의 한 변수의 영향을 알수도 있다. 고로 추론의 측면에서도 강점이 있다.

그러나 가법적인 모델이라는 점에서 중요한 상호작용을 잡아낼 수 없다는 단점이 있다. [가법성이란](https://stats.stackexchange.com/questions/260175/what-does-the-additive-assumption-mean)

문제 :
<img width="379" alt="nonlin3" src="https://user-images.githubusercontent.com/31824102/36206014-c03d27de-1188-11e8-828b-86a04cf46e58.PNG">
위 그림은 Wage~Age에 대해 piecewise constant로 적합한 회귀선과 그 SE로 구한 95% 신뢰띄입니다. 여기서 모델의 SE를 어떻게 구하였고 그걸로 어떻게 95%신뢰구간을 만들었을까요?

**Comment by angrypark** [comment]
답 : 7.2에서도 7.1에서 분산을 통해 점선을 추정한 방식과 같은 방식으로 추정했습니다. 즉, 적합된 계수 각각에 대한 분산 추정치들과 계수 추정치들 간의 공분산을 활용한 것이죠.
![image](https://user-images.githubusercontent.com/25877533/36210792-b749ae36-11e2-11e8-8d2d-16f960d713d4.png)
이 식까지 알필요는 없겠..죠?

면접 질문 
1. 모델에서 하나의 변수를 변환하는 방법에 대해 아는 것 있으면 알려주세요.
2. 변수가, 시간과 같이 그 전과 그 후가 매우 밀접한 관련이 있다면, 이를 어떻게 가중치를 둬서 회귀식을 짤수 있을까요?

**Comment by DabinJeong** [comment]
1. (Basis function approach에 관련된 질문인가요??사실 질문을 잘 이해를 못하겠습니다ㅠ)
    Polynomial regression에서는 n차식으로 변환 할수도 있고 precise constant function에서는 특정 상황일 때만 1이 되는 indicator function으로 변환할 수도 있습니다.

2. Local regression을 활용합니다. x0라는 점에 대해서 regression을 하는 경우 우선 전체 데이터 중 얼마 만큼을 쓸 지 정해줍니다 (s = k/n). 이 그룹안에 있는 각각의 점들에 대해 x0에서 가까우면 weight를 높게, 멀면 weight를 낮게 설정해서 x0에 가까울수록 regression에 더 큰 영향을 미치도록 합니다. 


문제
모델의 flexibility를 판단할 때 degree of freedom을 쓰는데, smoothing spline에서는 effective degrees of freedom을 쓰는 이유가 무엇인가요?
