### ISSUE TITLE
[DLCV] 2018-02-23 질문사항

### ISSUE THREAD

**Issue by KangBK0120** [YBIGTA/data-science-2018#16]
https://kangbk0120.github.io/articles/2018-02/cam

**Comment by SongChiYoung** [comment]
![image](https://user-images.githubusercontent.com/7540984/36602542-a2bed37c-18fb-11e8-8396-67dab8fdc0ab.png)
이 그림에 대한 설명
>>결국 어떤 class 로 분류될 확률을 구할 때 곱해지는 각각의 weight들을 feature map에 곱해준다음 이들을 합치면 무엇을 보고 이 feature map을 라고 분류했는지 알 수 있게 되는 것입니다.

이 잘 이해가 안됩니다.

feature map 이 variable 한 값 이고, weight가 constant한 값 일텐데(모델 학습 종료 이후 과정에서), 그림에서 보이는 feature map이 붉었던 부분이, Σ(feature map * weight) 이후 0가 되는 상황이 잘 이해되지 않습니다.

**Comment by hyejukim-ybigta** [comment]
앞부분에 나와있는 “얕은 곳에 있는 것은 edge를 찾아내고 깊어질수록 고차원적인 feature를 찾는다” 이 말에서 얕고 깊다는 의미가 어떤 의미인가요? 궁금합니다

**Comment by jungsooyun** [comment]
![default](https://user-images.githubusercontent.com/32008845/36624639-8a57edc4-1909-11e8-8f33-49a7ecc909b1.JPG)
치영이가 같은 질문을 해줬네요..! 같은 질문인데 위의 그림과 수식을 비교하는 중에 궁금해졌는데 저 그림이 나타내는 것이 f_k(x,y) 인건가요? 저 가중치와 feature map을 곱해주는 과정이 잘 이해가 되지 않습니다!

**Comment by godongyoung** [comment]
치영과 같은 그림에서, (w_k)^c의 의미가 잘이해되지않습니다ㅠ GAP를 거친후 하나의 FC를 거치고 softmax를하는것인가요?
또 flattening이 위치정보를 없앤다고보는것인지 궁금합니다. 위치정보라기보단 local한정보(주변애들을포함한 정보)를 구하는게 cnn이고 그렇게나온값 자체가 local정보를 가지고잇는것이니 flatten해줘도 되는것아닌가..이해햇엇는데, 혼란이왓습니다

**Comment by DabinJeong** [comment]
(w_k)^c는 어떤 방식으로 구하게 되나요? 수식이 잘 이해되지 않습니다..!
