### ISSUE TITLE
[ISL] 2018-02-23 질문사항

### ISSUE THREAD

**Issue by DabinJeong** [YBIGTA/data-science-2018#17]
https://github.com/YBIGTA/data-science-2018/blob/master/ISL/2018-02-23-DecisionTree.pdf

**Comment by SongChiYoung** [comment]
랜포에서, 앙상블 이후, 각 트리의 결과를 합치는 과정은 어떻게 되나요??
또. Boosting에서 weight를 정하는건 어떤 과정을 거치나요?

**Comment by KangBK0120** [comment]
RSS를 최소화할 때, greedy approach를 통해서 얻은 해(solution)가 항상 최적해인가요?

**Comment by Jooong** [comment]
![data-science-2018_2018-02-23-decisiontree_pdf_at_master_ _ybigta_data-science-2018_ _github](https://user-images.githubusercontent.com/19547969/36625038-5b29f446-195b-11e8-90be-39e9e90f3604.png)
모델의 Variance가 줄기 때문에 데이터에 덜 민감하게 되고, 따라서 generalization이 잘 되는 편이니깐 일반적으로 test-accuracy가 증가한다고 이해하면 될까요?
