### ISSUE TITLE
[ISL] 2018-01-13 질문사항

### ISSUE THREAD

**Issue by godongyoung** [YBIGTA/data-science-2018#2]
https://github.com/YBIGTA/data-science-2018/blob/master/ISL/An_Overview_of_Statistical_Learning_ch2.md

**Comment by Jooong** [comment]
![image](https://user-images.githubusercontent.com/19547969/34900316-2d5ea8e8-f842-11e7-9195-a393dfbae737.png)
자유도 개념좀 설명해주세여
