### ISSUE TITLE
[ISL 이론] 2018-03-17 질문사항

### ISSUE THREAD

**Issue by bohyunshin** [YBIGTA/data-science-2018#26]
[Linear Regression.pdf](https://github.com/YBIGTA/data-science-2018/files/1821242/Linear.Regression.pdf)

**Comment by SongChiYoung** [comment]
ISL 실습 has-const ?.?
https://stackoverflow.com/questions/30650257/ols-using-statsmodel-formula-api-versus-statsmodel-api/30651065
