### ISSUE TITLE
[ISL]2018-01-20 질문사항

### ISSUE THREAD

**Issue by angrypark** [YBIGTA/data-science-2018#4]
https://angrypark.github.io/ISL-study/
수식이 많아서 이걸로 보는게 정신건강에 좋을수도..

**Comment by statkim7578** [comment]
![22](https://user-images.githubusercontent.com/34841210/35157166-1253646a-fd2b-11e7-9453-de48eac97db1.PNG)
다중공선성 에서요
"두 개 이상의 설명변수들이 서로 밀접한 '상관'이 있는 경우를 말한다" 라고 하셨는데,
이 '상관'이라는게 두 변수간의 '직선관계' 만을 의미하는것인가요?

어떤 두 개의 설명변수들이 완벽한 '비선형적'인 관계를 갖고있다면, 다중공선성의 문제는 없는건가요?

**Comment by Jooong** [comment]
![image](https://user-images.githubusercontent.com/19547969/35159616-1f5a0850-fd7e-11e7-82b2-e9bf334fdb87.png)
1.제가 들은 계량경제학 수업에서는 [AutoRegressive 모델](https://datascienceschool.net/view-notebook/e880ecd416554dbf84db6a3e8f426b99/)등을 다루었는데, 더 복잡한 시계열 모형은 통계학과 분들이 설명해주실거라 믿습니다!

![image](https://user-images.githubusercontent.com/19547969/35159622-28be879a-fd7e-11e7-8289-8cd4580deb00.png)
2.아래 그래프를 이야기하는 건가 봅니다. 종속변수에 로그를 취해주어 이분산성을 잡아주었네요.
![image](https://user-images.githubusercontent.com/19547969/35159667-4bb1ebf2-fd7e-11e7-9aca-073262fd0fb8.png)

**Comment by godongyoung** [comment]
<img width="432" alt="question" src="https://user-images.githubusercontent.com/31824102/35161797-2afddd66-fd39-11e7-8ab1-713ff547693b.PNG">
해당 부분이 이해가 잘 가지 않습니다. 오차 error_i는 unknown 상수라서 correlate를 구할수 없지 않은지요?

**Comment by godongyoung** [comment]
@statkim7578 얘기한부분들 정리하여 올립니다!
때로 독립 변수는 다른 독립 변수 또는 데이터에 대해 비선형 함수이기도 합니다. 이러한 경우에도 이 독립 변수가 파라미터 벡터 β에 대해서만 선형이기만 하면 여전히 선형 모델이라 부릅니다. 대표적으로 X와 X^2항도 완벽한 비선형관계를 모델링한 경우입니다. 이것은 선형성 가정이 파라미터에 대한 선형성만을 가정하기 때문입니다. 따라서 완벽한 비선형관계 자체는  'colinearity가정'을 위반하지 않습니다. 다만 X와 X^2항의 경우를 비롯하여 상호작용항등 여러 추가항들이 빈번하게  '선형성'을 가져 다중공선성의 문제가 생길 수 있습니다.(X'X의 inverse matrix를 구할 수 없게 되므로) 이에 예측변수를 중심화한 모델링을 하는것이 좋습닌다

**Comment by KangBK0120** [comment]
![image](https://user-images.githubusercontent.com/25279765/35163730-16864b50-fd8b-11e7-8e99-4a42415eb7e6.png)

비선형 상관관계라는게 y와 x가 있을때 y=x^2같은 관계를 의미하는건가요?

다항식을 선형회귀한다는건 무슨 뜻인가요?

**Comment by ybigtaJH** [comment]
변수를 선택하는 고전적인 방식인 Forward Selection, Backward Selection, Stepwise Selection에 대해서 설명해주실 수 있나요??

**Comment by DabinJeong** [comment]
상관관계 vs 상호작용
둘 사이의 차이를 설명해주셨으면 좋겠습니다..!

**Comment by SongChiYoung** [comment]
> 다음의 그래프에 따르면, KNN은 상관관계가 선형적일 때는 선형회귀보다 약간 나쁘고 만약 비선형인 관계에서는 훨씬 좋다고 합니다. 즉, 관계가 선형적인지를 먼저 판단하고 만약 선형이라면 선형회귀를, 비선형이면 KNN을 하면 됩니다. 차원에 따라서 또 얘기는 달라지는데요, 설명변수의 수가 2개 이하면 KNN이 훨씬 좋고, 4개 이상이면 선형회귀가 더 좋다고 합니다.

우선, ```다음의 그래프```가 없습니다 ㅜㅜ.    
KNN 이 선형회귀보다 좋은 이유는 납득 가능합니다. 하지만, 설명변수의 차원에 따라 KNN의 효율성에 대해 직관적인 이해가 잘 안되어서, 추가적인 설명 부탁드립니다.

**Comment by jungsooyun** [comment]
어떤 상황에 낮은 R-Squared 값도 좋은 분석이 될 수 있는지는 아래 그림을 참조하면 좋습니다!
![default](https://user-images.githubusercontent.com/32008845/35179139-d1916bc8-fd8b-11e7-9ff3-f3ed8ccb8d0c.JPG)

두 경우 다 low p-value 이지만 하나는 R-square가 높은 경우, 하나는 낮은 경우입니다. 위와 같이 잔차의 분산이 매우 크더라도, trend가 확실한 경우에는 p-value가 적게 나타난다고 합니다. 낮은 R-square 값이 좋은 분석이 될 수 있는 경우는 경향성 그 자체가 중요한 경우고, 아닌 경우는 선형회귀 식을 통한 예측이 중요한 경우입니다.
 사회과학 연구를 예로 들면, Input이 나이, 반응 변수가 인터넷에서의 공격성(?)이라고 할 때, 낮은 설명력이 나와도 '나이가 많을 수록 공격성이 강해지는 경향이 있었다.'라고 얼버무릴 수 있는겁니다.
 하지만, 선형 회귀를 통해서 집값 예측을 한다고 할 때 설명력이 낮다면 'Input이 뭐뭐뭐일 때 집값은 1억원일꺼야 근데 이 예측된 집값의 95% 신뢰구간은 [3000만원, 1억 7천만원] 이란다~'꼴이 되어버리는 거죠.

**Comment by projokim** [comment]
양적 변수와 질적 변수가 무엇인지 설명해주실수 있을까요??

**Comment by statkim7578** [comment]
![1](https://user-images.githubusercontent.com/34841210/35179894-3a718ed8-fde7-11e7-803b-d806299426ec.PNG)
![2](https://user-images.githubusercontent.com/34841210/35179895-3beb59ce-fde7-11e7-913c-4a1ea6a16f5d.PNG)
![3](https://user-images.githubusercontent.com/34841210/35179896-3db62a04-fde7-11e7-91a1-23e552ec88d5.PNG)

다중공선성의 정의 참고하시면 좋을것 같아요!
