### ISSUE TITLE
[DLCV]2018-01-20 질문사항

### ISSUE THREAD

**Issue by Jooong** [YBIGTA/data-science-2018#5]
https://github.com/YBIGTA/data-science-2018/blob/master/DLCV/2018-01-20-Week-2.markdown

**Comment by KangBK0120** [comment]
H(x) - x라는데 H가 어떤 함수인가요? H가 residual unit이면 H(x) + x가 맞지않나요?

**Comment by SongChiYoung** [comment]
> ResNet은 residual block을 활용한 residual network입니다. 2015년 ILSVRC에서 우승하였고, "망이 깊어지는 것"에 대한 두려움으로 시작했다고 합니다. $$H(x)$$ 가 아닌 $$H(x)-x$$를 학습시킴으로서 한칸씩 뛰며 지름길을 만드는 형식인거죠. 관점을 잠깐 바꾼 것이지만 입력의 작은 움직임을 쉽게 검출할 수 있게 되면서 나머지(residual)을 학습한다는 관점에서 residual block이 됩니다. 이렇게 하면 깊은 망도 쉽게 최적화가 가능하고, 늘어난 깊이로 인해 정확도를 개선할 수 있습니다. 맞아요 엄청어려워요..
> 
ResNet 의 경우, 하나씩 건너뛰는데, 그럼 학습은 어떻게 이루어지게 되나요??

질문이 너무 추상적인거 같은데, 일반적인 백프로파게이션 으로는 어떻게 돌아가는지 머릿속에 잘 안그려져서..

**Comment by Jooong** [comment]
@SongChiYoung  residual block 안에서 백프롭 과정은 [여기](https://stackoverflow.com/questions/44512126/how-to-calculate-gradients-in-resnet-architecture)에 자세히 설명되어있는데요, 블록의 인풋과 레이어 하나 통과시킨 결과물을 **덧셈** 해준 것이라 자연스럽게 미분 되구요, 백프롭과정에서 다른 트릭이 필요하거나 하지는 않습니다.
residual block에 대한 자세한 설명은 [여기](https://github.com/YBIGTA/DeepNLP-Study/wiki/Day-02-Paper-Review:-ResNet)에서도 확인 가능합니다.

@KangBK0120 H(x)는 F(x)+x를 의미합니다. residual unit(혹은 residual block) 전체가 학습하는 함수고, F는 residual unit 내부의 첫 번째 레이어입니다.

**Comment by projokim** [comment]
max pooling과 average pooling은 일반적으로 차이나는 장단점이 있나요??

**Comment by hyejukim-ybigta** [comment]
이미지가 안보이는데 저만 그런가요 ㅠㅠ NIN에서 작은 network를 사용해서 1x1 convolutions size가 어떻게 나오는지 그 과정을 알 수 있을까요?

**Comment by godongyoung** [comment]
VGG에서 7 x 7필터를 3x3필터가 대체할수잇다는게 어떤의미인가요? 또 왜 그경우 3x3필터를 '3개'를 써주나요?

1x1 conv가 이해가잘가지않습니다ㅠ 그림으로보기엔 filter weight를 거치고 바로 sum을하는게 아니라 elementwise로 곱을하고 다시fc를 거치는것같은데..왜 이게 연산량을 더줄여주는지요??

**Comment by DabinJeong** [comment]
VGG를 사용하면 이전의 모델과는 다르게 여러 개의 ReLu를 사용할 수 있다는 말이 이해가 가지 않습니다..!

**Comment by KangBK0120** [comment]
@godongyoung  @hyejukim-ybigta 

https://kangbk0120.github.io/articles/2018-01/inception-googlenet-review
참고하세용, 연산량이 줄어드는 것은 1x1Conv를 사용해 차원을 축소한다음 다른 Conv연산을 적용하기 때문입니다

**Comment by Jooong** [comment]
@projokim 
> max pooling과 average pooling은 일반적으로 차이나는 장단점이 있나요??
이전에는 average pooling을 썼지만 요새는 max pooling을 더 많이 쓰는 것 같습니다. 장단점에 대해서는 잘 모르겠습니다만, [Grad-cam](https://arxiv.org/abs/1610.02391) 등, 네트워크가 특정 판단을 내린 이유 등을 추적하기 위한 작업을 할 때는 avg pooling을 쓰는 것 같습니다.

@hyejukim-ybigta 
> 이미지가 안보이는데 저만 그런가요 ㅠㅠ NIN에서 작은 network를 사용해서 1x1 convolutions size가 어떻게 나오는지 그 과정을 알 수 있을까요?
1x1 conv를 사용하는 경우, 이미지의 가로 세로 사이즈는 보존됩니다. 모든 픽셀에 대해서 1x1사이즈의 필터를 덧대주기 때문이죠. 이 때 사용한 필터의 개수가 channel 사이즈가 되고, 이 필터 개수를 통해서 원래 이미지 텐서의 채널 사이즈를 조절할 수가 있습니다.

@godongyoung
>1x1 conv가 이해가잘가지않습니다ㅠ 그림으로보기엔 filter weight를 거치고 바로 sum을하는게 아니라 elementwise로 곱을하고 다시fc를 거치는것같은데..왜 이게 연산량을 더줄여주는지요??
위 설명처럼, 1x1 필터를 적용하면 필터 개수를 통해서 원래 이미지 텐서의 차원을 조절할 수 있습니다. 1x1 conv로 채널 수를 줄인 후 5x5 필터를 적용하면 필요한 연산 수를 줄일 수가 있습니다.

![image](https://user-images.githubusercontent.com/19547969/35180234-95756ae0-fdef-11e7-87d5-84c60fa5758e.png)

위에서처럼 큰 차원에 5x5 필터를 적용하면 120m 개의 파라미터가 필요합니다.

![image](https://user-images.githubusercontent.com/19547969/35180245-e05f2c4e-fdef-11e7-84fc-fc1268cb24a9.png)

위에서처럼 큰 차원에 1x1 필터로 채널 수를 줄이고 5x5 필터를 적용하면 12.4m 개의 파라미터가 필요합니다.
