### ISSUE TITLE
[DLCV]2018-01-27 질문사항

### ISSUE THREAD

**Issue by KangBK0120** [YBIGTA/data-science-2018#6]
https://kangbk0120.github.io/articles/2018-01/dlcv-week3

**Comment by godongyoung** [comment]
FC대신 convolution을 하는 부분에서,  5x5x16을 flatten하는 대신 5x5의 필터를 사용하면 1x1x400의 값을 얻을 수 있다는 부분이 잘 이해가 안됩니다ㅠ

Sliding Window Detection을 언급하면서 많은 연산량이 단점이라 했었는데요, conv로 대체한 모델이 이 단점을 어떻게 극복한것인가요? crop을 할필요가 없기에 crop에 대한 연산이 줄었다는 의미인가요?

**Comment by statkim7578** [comment]
![seg](https://user-images.githubusercontent.com/34841210/35451387-5e2f4562-0306-11e8-8bb0-967799a4a795.PNG)
이미지를 segmentation해서 배경이 아닌 물체들을 파악하는것은 어떻게 수행되나요?

**Comment by KangBK0120** [comment]
@godongyoung 

1. 5x5x16의 feature map에서 5x5필터를 사용한 convolution연산을 적용하기 위해서는 필터의 크기가 5x5x16이어야 합니다. 이러한 필터를 400개 사용하게 되면 1x1x400을 얻을 수 있다는 의미입니다. 이게 곧 FC와 동일하다고 볼 수 있죠. FC의 그림을 그려봤을 때 input의 모든 노드에서 output의 한 노드로 대응되는 연산이 필터 하나의 연산과 동일합니다. FC에서는 쭉 펼친 feature 맵에서 element-wise의 연산을 수행하고, 필터에서도 쭉 펼치진 않았지만 element-wise의 연산을 수행하니까요.

2. 넵 말씀하신게 맞습니다. 고전적인 Sliding Window의 경우에는 특정한 Window만큼의 사이즈를 Crop한다음에 분류했습니다. 하지만 Convolution연산을 적용하게 되면 이미지를 Crop할 필요없이 한번에 처리할 수 있게 됩니다. 

@statkim7578 

https://tensorflow.blog/2017/06/05/from-r-cnn-to-mask-r-cnn/

![image](https://user-images.githubusercontent.com/25279765/35454598-057b97c0-0312-11e8-8b84-6cdc3583cbc9.png)

이 글을 읽어보시면 이해가 빠르실 것같은데요, 간단히 말하면 인접한 픽셀의 색상이나 강도 등을 보고 여러 개의 바운딩박스를 추천해줍니다. 왼쪽의 semantic segmentation을 생각하시면 됩니다. 물론 질문하신 그림보다 훨씬 더 많은 바운딩 박스가 그려질 것이고, 이후에 이를 네트워크에 넣어 물체를 판단합니다.

**Comment by hyejukim-ybigta** [comment]
마지막으로 이 물체가 어떤 class에 속하는지를 출력합니다. 우리는 총 4개의 class를 예측하려 했지만 배경은 Pc 가 0인 경우에 포함되므로 나머지 3개를 예측해주면 됩니다. <- 이 부분 잘 이해가 안되는데 그 위 슬라이드에서 C1,C2,C3 이 class 분류를 하는 것인가요??

**Comment by ybigtaJH** [comment]
YOLO Algorithm에서
"bh,bw 의 경우에는 물체가 여러 그리드에 걸쳐있을 수 있으므로 1보다 클 수도 있습니다."가 이해가 안됩니다ㅜㅜ

**Comment by DabinJeong** [comment]
앵커 박스를 설정할 때,  사람이 임의로 형태를 정의해 주고 자동차의 경우는 가로로 긴 엥커 박스가 사용된다고 하셨는데 그렇게 되면 자동차의 옆모습만 잡아낼 수 있는 건가요?? 형태가 다양한 물체에 대해서는 앵커박스가 어떻게 설정되는 지 궁금합니다.

**Comment by SongChiYoung** [comment]
색이 스무딩 되어있을 때
그러니까, 눈 온 배경에 흰 차 같은 겅우엔 어떻게 엥커 박스가 추천될까요.

![](https://cdn-images-1.medium.com/max/1600/1*2SWb6CmxzbPZijmevFbe-g.jpeg)
