### ISSUE TITLE
[ISL]2018-01-27 질문사항

### ISSUE THREAD

**Issue by godongyoung** [YBIGTA/data-science-2018#7]
4장 : https://github.com/ybigtaJH/ISL_STUDY/blob/master/ISL_Chapter4.pdf
5장 : https://godongyoung.github.io/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D/2018/01/26/%EB%B0%9C%EC%A0%9C%EC%9A%A9ch5-Resampling-method.html

**Comment by Jooong** [comment]
마크다운 이미지 삽입하실 때 `![어쩌구](img_url)` 와 같은 형식으로 입력하시면 이미지가 문서에서 바로 보이게 됩니다. 앞에 느낌표가 없으면 `어쩌구`라는 문자에 이미지 url이 하이퍼링크가 걸려요.

**Comment by Jooong** [comment]
![ch5_resampling_method_ _go_s_blog](https://user-images.githubusercontent.com/19547969/35438248-1e2e38d8-02d9-11e8-82e2-1c3b9a00af63.png)

1. 중요한 건 아니지만,  수식에서 Cov 항에 2를 곱해주어야 할 것 같습니다.
2. 그 아래 줄 식은 argmin[f(a)]가 맞는 표현이지 싶습니다. 이 때 1계 조건을 고려해서 df(a)/da = 0이 되는 a를 찾는거구요.

**Comment by KangBK0120** [comment]
![image](https://user-images.githubusercontent.com/25279765/35454318-e2cd6484-0310-11e8-9cf5-3f98cc4a84e3.png)

클래스가 잘 나누어져 있다는게 무슨 뜻인가요? 2개의 클래스가 있다고 했을 때 반반으로 나뉘는게 잘 나누어져 있는 경우인가요?

**Comment by godongyoung** [comment]
@Jooong  오오 맞습니다 오류지적감사합니다! 급하게쓰느라 검토를못햇네요ㅠ 수정하겠습니다~

**Comment by SongChiYoung** [comment]
MSE 는 음수도 나올 수 있을거 같은데,
시구자로 처리했을때 이 처리는 어떻게 되나요
