### ISSUE TITLE
[ISL]2018-02-03 질문사항

### ISSUE THREAD

**Issue by statkim7578** [YBIGTA/data-science-2018#9]
발제자료를 pdf파일로만 export할 수 있어서, 어쩔수없이 pdf로 업로드했습니다..!
로딩시간이 길 수도 있으니 아래 링크에서
Download 버튼으로 다운 후 봐주시면 감사하겠습니다.

https://github.com/YBIGTA/data-science-2018/blob/master/ISL/%5B2018-02-03%5DChapter6.pdf

아 그리고 6장 내용이 워낙 길다보니
아래 pdf파일의 다음 부분만 발제할 예정입니다! 

intro부분 = 3쪽~4쪽
Ridge regression, Lasso regression = 12쪽 ~ 20쪽

이 부분을 읽어주시고 코멘트 부탁드리겠습니당

**Comment by projokim** [comment]
1. Ridge regression과 변수 selection을 같이 사용하기도 하나요? 만약 그렇다면 Lasso Regression과 많은 차이를 보이나요??

2. Ridge regression과  Lasso Regression에서 Ridge가 Lasso와 달리 계수추정치가 0이 아니고 0에 가까워지는 이유가 궁금합니다. 수축 패널티에서, Ridge는 제곱이 있으므로 0.1의 경우 0.01이 되니 효과가 더 크므로,계수가 0이 되지 않아도 1보다 어느정도 작아지면 충분히 효과가 있으므로라고 해석해도 될까요?

**Comment by KangBK0120** [comment]
Ordinary Least Squares Regression에서 모형개선의 여지가 없다는 건 새로운 데이터/관측치가 들어왔을때 모델을 완전히 새로 fitting 시켜줘야한다는 의미인가요?

**Comment by KangBK0120** [comment]
1. Ordinary Linear Regression에서 모형개선의 여지가 없다는 것은 hyperparamter가 없으므로 똑같은 데이터에 대해 똑같은 결과만을 얻을 수 있다는 의미인가요?
2. Ridge나 Lasso에서 최적의 lambda를 선택하기 위해서는 trial-and-error로 여러 값을 넣고 결과를 봐야만 하나요?

**Comment by Jooong** [comment]
lasso / ridge에서 (1)람다를 이용한 penalty 방식과 (2)t를 이용한 constraint 방식을 각각 (1)라그랑제 승수를 이용한 unconstrained 문제와 (2)부등식 조건이 달린 constrained 문제라고 해석해도 될까요?

**Comment by angrypark** [comment]
@KangBK0120  1. 응 2. 최적의 lambda를 선택한다기 보다는 lambda에 따라 ridge lasso가 달라진다고 생각하면 될듯 hyperparameter는 마즘

https://www.quora.com/In-ridge-regression-and-lasso-what-is-lambda

lambda is the penalty coefficient and it’s free to take any allowed number while alpha is selected based on the model you want to try .

So if we take alpha = 0, it will become Ridge and alpha = 1 is LASSO and anything between 0–1 is Elastic net. Now how to decide Lambda. So when we run “Cross Validation” on the data we get 100 combination of Lambda and their corresponding Mean squared Error.

**Comment by jungsooyun** [comment]
@projokim 

2. https://stats.stackexchange.com/questions/74542/why-does-the-lasso-provide-variable-selection
![default](https://user-images.githubusercontent.com/32008845/35762919-7dad6576-0898-11e8-9e6e-8262d20d65e2.JPG)
위의 베타 추정량은 lasso의 추정량이고
![default](https://user-images.githubusercontent.com/32008845/35762945-121b306c-0899-11e8-8f58-5a4dc21296c8.JPG)
위의 베타 추정량이 ridge의 추정량이라고 합니다.

lasso의 추정량은 각 계수의 값들이 람다에 비례에 선형적으로 감소하기 때문에 계수 크기에 따라 0에 도달하는 속도가 다르고,
ridge의 추정량은 각 계수의 값들이 람다에 반비례해 감소하기 때문에 같은 지점에서 0에 도달한다..라고 생각하시면 될 것 같습니다.
